service: rohawolf-sls-ws

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${self:opt.stage, "dev"}
  region: ${self:opt.region, "ap-northeast-2"}
  websocketsApiName: ${self:service}-${self:provider.stage}
  websocketsApiRouteSelectionExpression: $request.body.action
  
functions:
  connectionHandler:
    handler: handler.connectionHandler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect

  defaultHandler:
    handler: handler.defaultHandler
    events:
      - websocket: $default

  echoHandler:
    handler: handler.echoHandler
    events:
      - websocket:
          route: echo